// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ITCompliance.API.Models;

public partial class Employee
{
    public int Id { get; set; }

    public string EmployeeId { get; set; }

    public string Name { get; set; }

    public string Department { get; set; }

    public string Designation { get; set; }

    public string Role { get; set; }

    public string PasswordHash { get; set; }

    public string CellularId { get; set; }

    public string DeviceName { get; set; }

    public string IpAddress { get; set; }

    public string LanLaptopId { get; set; }

    public string LanMacId { get; set; }
}