// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ITCompliance.API.Models;

public partial class InternetAccessRequest
{
    public int Id { get; set; }

    public string EmployeeId { get; set; }

    public string Website { get; set; }

    public string Reason { get; set; }

    public string Duration { get; set; }

    public string Status { get; set; }

    public string ITOfficerRemarks { get; set; }

    public string HODRemarks { get; set; }

    public string BossRemarks { get; set; }

    public string SecurityHeadRemarks { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string CellularId { get; set; }

    public string DeviceName { get; set; }

    public string IpAddress { get; set; }

    public string LanLaptopId { get; set; }

    public string LanMacId { get; set; }

    public string EmployeeEmail { get; set; }

    public string DepartmentCode { get; set; }

    // Which department's HOD queue this currently belongs to. Set at
    // submit time (requester's own dept) and again when the request
    // reaches the final IT-HOD stage (set to Workflow:ItDepartmentCode).
    // Null while awaiting IT Officer/Security Head, since that stage
    // isn't department-scoped.
    public string PendingDepartmentCode { get; set; }
}