// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ITCompliance.API.Models;

public partial class ITcomplianceDBContext : DbContext
{
    public ITcomplianceDBContext()
    {
    }

    public ITcomplianceDBContext(DbContextOptions<ITcomplianceDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<InternetAccessRequest> InternetAccessRequests { get; set; }

    public virtual DbSet<OES_vuEmployeeDetail> OES_vuEmployeeDetails { get; set; }

    public virtual DbSet<tbl_Employee> tbl_Employees { get; set; }

    public virtual DbSet<tbl_HODdetail> tbl_HODdetails { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Employee__3214EC07E2D5F5A1");

            entity.Property(e => e.CellularId).IsRequired();
            entity.Property(e => e.Department).IsRequired();
            entity.Property(e => e.Designation).IsRequired();
            entity.Property(e => e.DeviceName).IsRequired();
            entity.Property(e => e.EmployeeId).IsRequired();
            entity.Property(e => e.IpAddress).IsRequired();
            entity.Property(e => e.LanLaptopId).IsRequired();
            entity.Property(e => e.LanMacId).IsRequired();
            entity.Property(e => e.Name).IsRequired();
            entity.Property(e => e.PasswordHash).IsRequired();
            entity.Property(e => e.Role).IsRequired();
        });

        modelBuilder.Entity<InternetAccessRequest>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Internet__3214EC0717FD6684");

            entity.Property(e => e.CellularId)
                .IsRequired()
                .HasDefaultValue("");
            entity.Property(e => e.DeviceName)
                .IsRequired()
                .HasDefaultValue("");
            entity.Property(e => e.Duration).IsRequired();
            entity.Property(e => e.EmployeeEmail)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_InternetAccessRequests_EmployeeEmail");
            entity.Property(e => e.EmployeeId).IsRequired();
            entity.Property(e => e.IpAddress)
                .IsRequired()
                .HasDefaultValue("");
            entity.Property(e => e.LanLaptopId)
                .IsRequired()
                .HasDefaultValue("");
            entity.Property(e => e.LanMacId)
                .IsRequired()
                .HasDefaultValue("");
            entity.Property(e => e.Reason).IsRequired();
            entity.Property(e => e.Status).IsRequired();
            entity.Property(e => e.Website).IsRequired();
        });

        modelBuilder.Entity<OES_vuEmployeeDetail>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("OES_vuEmployeeDetails");

            entity.Property(e => e.DepartmentCode)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.DepartmentName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Designation)
                .IsRequired()
                .HasMaxLength(35);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.EmpId)
                .IsRequired()
                .HasMaxLength(25);
            entity.Property(e => e.LocationCode)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.LocationName)
                .IsRequired()
                .HasMaxLength(60);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.RegionCode)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.RegionName)
                .IsRequired()
                .HasMaxLength(60);
        });

        modelBuilder.Entity<tbl_Employee>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("tbl_Employee");

            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.Dept).HasMaxLength(5);
            entity.Property(e => e.DeviceId).HasMaxLength(50);
            entity.Property(e => e.DeviceStatus).HasMaxLength(50);
            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EmpId)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EmpName)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Id).ValueGeneratedOnAdd();
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.Password)
                .HasMaxLength(1000)
                .IsUnicode(false);
        });

        modelBuilder.Entity<tbl_HODdetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_HODd__3214EC07FFD0E1A1");

            entity.Property(e => e.DeptCode).HasMaxLength(20);
            entity.Property(e => e.DeptName).HasMaxLength(128);
            entity.Property(e => e.DirectorEmail).HasMaxLength(100);
            entity.Property(e => e.DirectorEmpId).HasMaxLength(50);
            entity.Property(e => e.DirectorName).HasMaxLength(50);
            entity.Property(e => e.HODemail).HasMaxLength(100);
            entity.Property(e => e.HODempID).HasMaxLength(50);
            entity.Property(e => e.HODname).HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}