// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ITCompliance.API.Models;

public partial class tbl_HODdetail
{
    public int Id { get; set; }

    public string DeptCode { get; set; }

    public string DeptName { get; set; }

    public string HODempID { get; set; }

    public string HODname { get; set; }

    public string HODemail { get; set; }

    public string DirectorEmpId { get; set; }

    public string DirectorName { get; set; }

    public string DirectorEmail { get; set; }
}