// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ITCompliance.API.Models;

public partial class tbl_Employee
{
    public long Id { get; set; }

    public string EmpId { get; set; }

    public string EmpName { get; set; }

    public string Password { get; set; }

    public string Email { get; set; }

    public int? UserTypeId { get; set; }

    public bool? IsADUser { get; set; }

    public long? ReportToUserId { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedOn { get; set; }

    public long? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public long? ModifiedBy { get; set; }

    public int? Version { get; set; }

    public string Dept { get; set; }

    public bool? LogIn { get; set; }

    public bool? LogOut { get; set; }

    public string DeviceStatus { get; set; }

    public string DeviceId { get; set; }
}